# Generated by Django 6.0.4 on 2026-04-30 13:38

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("callout", 10),
                            ("columns", 14),
                            ("divider", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("h2", "H2"), ("h3", "H3")],
                                    "label": "سطح عنوان",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.RichTextBlock", (), {"label": "متن"}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "تصویر", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "کپشن", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full", "تمام عرض"),
                                        ("left", "چپ"),
                                        ("right", "راست"),
                                    ],
                                    "label": "چیدمان",
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("alignment", 6)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "متن", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 8), ("text", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {"icon": "horizontalrule", "label": "خط جداکننده"},
                            ),
                            12: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 2),
                                        ("rich_text", 3),
                                        ("image", 7),
                                        ("callout", 10),
                                        ("divider", 11),
                                    ]
                                ],
                                {"label": "ستون چپ", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 2),
                                        ("rich_text", 3),
                                        ("image", 7),
                                        ("callout", 10),
                                        ("divider", 11),
                                    ]
                                ],
                                {"label": "ستون راست", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("left", 12), ("right", 13)]],
                                {},
                            ),
                        },
                        verbose_name="محتوا",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحه درباره ما",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(blank=True, verbose_name="متن معرفی"),
                ),
            ],
            options={
                "verbose_name": "صفحه لیست بلاگ",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="ContactPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("section", 20),
                            ("heading", 3),
                            ("rich_text", 4),
                            ("image", 8),
                            ("callout", 11),
                            ("columns", 15),
                            ("divider", 12),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان بخش", "required": False},
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("h2", "H2"), ("h3", "H3")],
                                    "label": "سطح عنوان",
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 1), ("level", 2)]],
                                {},
                            ),
                            4: ("wagtail.blocks.RichTextBlock", (), {"label": "متن"}),
                            5: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "تصویر", "required": True},
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "کپشن", "required": False},
                            ),
                            7: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full", "تمام عرض"),
                                        ("left", "چپ"),
                                        ("right", "راست"),
                                    ],
                                    "label": "چیدمان",
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 5), ("caption", 6), ("alignment", 7)]],
                                {},
                            ),
                            9: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان", "required": False},
                            ),
                            10: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "متن", "required": True},
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 9), ("text", 10)]],
                                {},
                            ),
                            12: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {"icon": "horizontalrule", "label": "خط جداکننده"},
                            ),
                            13: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 3),
                                        ("rich_text", 4),
                                        ("image", 8),
                                        ("callout", 11),
                                        ("divider", 12),
                                    ]
                                ],
                                {"label": "ستون چپ", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 3),
                                        ("rich_text", 4),
                                        ("image", 8),
                                        ("callout", 11),
                                        ("divider", 12),
                                    ]
                                ],
                                {"label": "ستون راست", "required": False},
                            ),
                            15: (
                                "wagtail.blocks.StructBlock",
                                [[("left", 13), ("right", 14)]],
                                {},
                            ),
                            16: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان زیر\u200cبخش", "required": False},
                            ),
                            17: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 3),
                                        ("rich_text", 4),
                                        ("image", 8),
                                        ("callout", 11),
                                        ("divider", 12),
                                    ]
                                ],
                                {"label": "محتوای زیر\u200cبخش", "required": False},
                            ),
                            18: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 16), ("body", 17)]],
                                {
                                    "icon": "folder-open-inverse",
                                    "label": "زیر\u200cبخش",
                                    "template": "cms/blocks/section_inner.html",
                                },
                            ),
                            19: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 3),
                                        ("rich_text", 4),
                                        ("image", 8),
                                        ("callout", 11),
                                        ("columns", 15),
                                        ("divider", 12),
                                        ("section", 18),
                                    ]
                                ],
                                {"label": "محتوا", "required": False},
                            ),
                            20: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("body", 19)]],
                                {},
                            ),
                        },
                        verbose_name="محتوا",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحه تماس با ما",
            },
            bases=("wagtailcore.page",),
        ),
        migrations.CreateModel(
            name="BlogPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("excerpt", models.TextField(blank=True, verbose_name="خلاصه")),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("heading", 2),
                            ("rich_text", 3),
                            ("image", 7),
                            ("callout", 10),
                            ("columns", 14),
                            ("divider", 11),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان", "required": True},
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("h2", "H2"), ("h3", "H3")],
                                    "label": "سطح عنوان",
                                },
                            ),
                            2: (
                                "wagtail.blocks.StructBlock",
                                [[("text", 0), ("level", 1)]],
                                {},
                            ),
                            3: ("wagtail.blocks.RichTextBlock", (), {"label": "متن"}),
                            4: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"label": "تصویر", "required": True},
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "کپشن", "required": False},
                            ),
                            6: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("full", "تمام عرض"),
                                        ("left", "چپ"),
                                        ("right", "راست"),
                                    ],
                                    "label": "چیدمان",
                                },
                            ),
                            7: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 4), ("caption", 5), ("alignment", 6)]],
                                {},
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"label": "عنوان", "required": False},
                            ),
                            9: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"label": "متن", "required": True},
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 8), ("text", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.static_block.StaticBlock",
                                (),
                                {"icon": "horizontalrule", "label": "خط جداکننده"},
                            ),
                            12: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 2),
                                        ("rich_text", 3),
                                        ("image", 7),
                                        ("callout", 10),
                                        ("divider", 11),
                                    ]
                                ],
                                {"label": "ستون چپ", "required": False},
                            ),
                            13: (
                                "wagtail.blocks.StreamBlock",
                                [
                                    [
                                        ("heading", 2),
                                        ("rich_text", 3),
                                        ("image", 7),
                                        ("callout", 10),
                                        ("divider", 11),
                                    ]
                                ],
                                {"label": "ستون راست", "required": False},
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [[("left", 12), ("right", 13)]],
                                {},
                            ),
                        },
                        verbose_name="متن",
                    ),
                ),
                (
                    "featured_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="تصویر شاخص (اختیاری)",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست بلاگ",
            },
            bases=("wagtailcore.page",),
        ),
    ]
