# Generated by Django 6.0.4 on 2026-04-30 13:40

import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="author",
            field=models.CharField(blank=True, max_length=100, verbose_name="نویسنده"),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="published_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="views",
            field=models.IntegerField(default=0, verbose_name="تعداد بازدید"),
        ),
        migrations.AlterField(
            model_name="aboutpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("rich_text", 3),
                    ("image", 7),
                    ("callout", 10),
                    ("columns", 14),
                    ("divider", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3")], "label": "سطح عنوان"},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"label": "متن"}),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "تصویر", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "کپشن", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "تمام عرض"),
                                ("left", "چپ"),
                                ("right", "راست"),
                            ],
                            "label": "چیدمان",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("alignment", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "متن", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("text", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"icon": "horizontalrule", "label": "خط جداکننده"},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 2),
                                ("rich_text", 3),
                                ("image", 7),
                                ("callout", 10),
                                ("divider", 11),
                            ]
                        ],
                        {"label": "ستون چپ", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 2),
                                ("rich_text", 3),
                                ("image", 7),
                                ("callout", 10),
                                ("divider", 11),
                            ]
                        ],
                        {"label": "ستون راست", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 12), ("right", 13)]],
                        {},
                    ),
                    15: ("cms.models.DividerBlock", (), {}),
                },
                verbose_name="محتوا",
            ),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", 2),
                    ("rich_text", 3),
                    ("image", 7),
                    ("callout", 10),
                    ("columns", 14),
                    ("divider", 15),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان", "required": True},
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3")], "label": "سطح عنوان"},
                    ),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 0), ("level", 1)]],
                        {},
                    ),
                    3: ("wagtail.blocks.RichTextBlock", (), {"label": "متن"}),
                    4: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "تصویر", "required": True},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "کپشن", "required": False},
                    ),
                    6: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "تمام عرض"),
                                ("left", "چپ"),
                                ("right", "راست"),
                            ],
                            "label": "چیدمان",
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 4), ("caption", 5), ("alignment", 6)]],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان", "required": False},
                    ),
                    9: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "متن", "required": True},
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 8), ("text", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"icon": "horizontalrule", "label": "خط جداکننده"},
                    ),
                    12: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 2),
                                ("rich_text", 3),
                                ("image", 7),
                                ("callout", 10),
                                ("divider", 11),
                            ]
                        ],
                        {"label": "ستون چپ", "required": False},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 2),
                                ("rich_text", 3),
                                ("image", 7),
                                ("callout", 10),
                                ("divider", 11),
                            ]
                        ],
                        {"label": "ستون راست", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 12), ("right", 13)]],
                        {},
                    ),
                    15: ("cms.models.DividerBlock", (), {}),
                },
                verbose_name="متن",
            ),
        ),
        migrations.AlterField(
            model_name="contactpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("section", 21),
                    ("heading", 3),
                    ("rich_text", 4),
                    ("image", 8),
                    ("callout", 11),
                    ("columns", 15),
                    ("divider", 16),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان بخش", "required": False},
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {"choices": [("h2", "H2"), ("h3", "H3")], "label": "سطح عنوان"},
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 1), ("level", 2)]],
                        {},
                    ),
                    4: ("wagtail.blocks.RichTextBlock", (), {"label": "متن"}),
                    5: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "تصویر", "required": True},
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "کپشن", "required": False},
                    ),
                    7: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("full", "تمام عرض"),
                                ("left", "چپ"),
                                ("right", "راست"),
                            ],
                            "label": "چیدمان",
                        },
                    ),
                    8: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 5), ("caption", 6), ("alignment", 7)]],
                        {},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان", "required": False},
                    ),
                    10: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {"label": "متن", "required": True},
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 9), ("text", 10)]],
                        {},
                    ),
                    12: (
                        "wagtail.blocks.static_block.StaticBlock",
                        (),
                        {"icon": "horizontalrule", "label": "خط جداکننده"},
                    ),
                    13: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("rich_text", 4),
                                ("image", 8),
                                ("callout", 11),
                                ("divider", 12),
                            ]
                        ],
                        {"label": "ستون چپ", "required": False},
                    ),
                    14: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("rich_text", 4),
                                ("image", 8),
                                ("callout", 11),
                                ("divider", 12),
                            ]
                        ],
                        {"label": "ستون راست", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("left", 13), ("right", 14)]],
                        {},
                    ),
                    16: ("cms.models.DividerBlock", (), {}),
                    17: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "عنوان زیر\u200cبخش", "required": False},
                    ),
                    18: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("rich_text", 4),
                                ("image", 8),
                                ("callout", 11),
                                ("divider", 16),
                            ]
                        ],
                        {"label": "محتوای زیر\u200cبخش", "required": False},
                    ),
                    19: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 17), ("body", 18)]],
                        {
                            "icon": "folder-open-inverse",
                            "label": "زیر\u200cبخش",
                            "template": "cms/blocks/section_inner.html",
                        },
                    ),
                    20: (
                        "wagtail.blocks.StreamBlock",
                        [
                            [
                                ("heading", 3),
                                ("rich_text", 4),
                                ("image", 8),
                                ("callout", 11),
                                ("columns", 15),
                                ("divider", 16),
                                ("section", 19),
                            ]
                        ],
                        {"label": "محتوا", "required": False},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("body", 20)]],
                        {},
                    ),
                },
                verbose_name="محتوا",
            ),
        ),
    ]
