# Generated by Django 6.0.2 on 2026-02-12 15:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=200, verbose_name="نام و نام خانوادگی"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تلفن باید به فرمت 09xxxxxxxxx باشد",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره تماس",
                    ),
                ),
                (
                    "phone_number_2",
                    models.CharField(
                        blank=True, max_length=11, verbose_name="شماره تماس دوم"
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                (
                    "additional_notes",
                    models.TextField(blank=True, verbose_name="یادداشت\u200cهای اضافی"),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=0, max_digits=12, verbose_name="مبلغ کل"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("pending", "در انتظار پرداخت"),
                            ("purchased", "پرداخت شده"),
                            ("processing", "در حال پردازش"),
                            ("shipped", "ارسال شده"),
                            ("delivered", "تحویل داده شده"),
                            ("cancelled", "لغو شده"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="شماره کارت پرداخت"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="شماره پیگیری"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "purchased_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارشات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="نامک"
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="زیرعنوان"
                    ),
                ),
                ("description", models.TextField(verbose_name="توضیحات")),
                (
                    "category",
                    models.CharField(
                        choices=[("coffee", "قهوه"), ("chocolate", "شکلات")],
                        max_length=20,
                        verbose_name="دسته\u200cبندی",
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(
                        upload_to="products/main/", verbose_name="تصویر اصلی"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت (تومان)"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("stock", models.IntegerField(default=0, verbose_name="موجودی")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "محصول",
                "verbose_name_plural": "محصولات",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        max_length=16, verbose_name="شماره کارت دریافت وجه"
                    ),
                ),
                (
                    "card_holder_name",
                    models.CharField(max_length=200, verbose_name="نام صاحب کارت"),
                ),
                (
                    "bank_name",
                    models.CharField(max_length=100, verbose_name="نام بانک"),
                ),
                (
                    "contact_phone",
                    models.CharField(max_length=11, verbose_name="شماره تماس"),
                ),
                (
                    "contact_email",
                    models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
                ),
                ("address", models.TextField(blank=True, verbose_name="آدرس")),
            ],
            options={
                "verbose_name": "تنظیمات سایت",
                "verbose_name_plural": "تنظیمات سایت",
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="تعداد"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="قیمت واحد"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="website.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "آیتم سفارش",
                "verbose_name_plural": "آیتم\u200cهای سفارش",
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products/gallery/", verbose_name="تصویر"
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="متن جایگزین"
                    ),
                ),
                ("order", models.IntegerField(default=0, verbose_name="ترتیب")),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="website.product",
                        verbose_name="محصول",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر محصول",
                "verbose_name_plural": "تصاویر محصولات",
                "ordering": ["order"],
            },
        ),
    ]
