# Generated by Django 6.0.2 on 2026-02-12 18:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="نامک"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(max_length=300, verbose_name="خلاصه مطلب"),
                ),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "featured_image",
                    models.ImageField(upload_to="blog/", verbose_name="تصویر شاخص"),
                ),
                (
                    "author",
                    models.CharField(
                        default="تیم ژیناد", max_length=100, verbose_name="نویسنده"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="تعداد بازدید")),
            ],
            options={
                "verbose_name": "مقاله",
                "verbose_name_plural": "مقالات مجله",
                "ordering": ["-published_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="admin_notes",
            field=models.TextField(blank=True, verbose_name="یادداشت ادمین"),
        ),
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ تایید"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="telegram_notified",
            field=models.BooleanField(
                default=False, verbose_name="اعلان تلگرام ارسال شده"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="کد پیگیری سفارش"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="telegram_bot_token",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="توکن ربات تلگرام"
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Chat ID تلگرام"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "پیش\u200cنویس"),
                    ("pending", "در انتظار پرداخت"),
                    ("purchased", "پرداخت شده - در انتظار تایید"),
                    ("confirmed", "تایید شده"),
                    ("processing", "در حال آماده\u200cسازی"),
                    ("shipped", "ارسال شده"),
                    ("delivered", "تحویل داده شده"),
                    ("cancelled", "لغو شده"),
                ],
                default="draft",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="شماره پیگیری تراکنش"
            ),
        ),
    ]
