# Generated by Django 6.0.2 on 2026-02-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_blogpost_order_admin_notes_order_confirmed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام گیرنده")),
                (
                    "platform",
                    models.CharField(
                        choices=[("telegram", "تلگرام"), ("bale", "بله")],
                        max_length=20,
                        verbose_name="پلتفرم",
                    ),
                ),
                ("chat_id", models.CharField(max_length=100, verbose_name="شناسه چت")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "گیرنده اعلان",
                "verbose_name_plural": "گیرندگان اعلان",
                "ordering": ["platform", "name"],
            },
        ),
        migrations.RemoveField(
            model_name="sitesettings",
            name="telegram_chat_id",
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="bale_bot_token",
            field=models.CharField(
                blank=True, max_length=200, verbose_name="توکن ربات بله"
            ),
        ),
    ]
