# Generated by Django 6.0.4 on 2026-04-30 12:29

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def forwards_create_categories(apps, schema_editor):
    Product = apps.get_model("website", "Product")
    Category = apps.get_model("website", "Category")

    mapping = {
        "coffee": "قهوه",
        "chocolate": "شکلات",
    }

    # create categories (including any unexpected legacy values)
    legacy_values = (
        Product.objects.exclude(category__isnull=True)
        .exclude(category__exact="")
        .values_list("category", flat=True)
        .distinct()
    )

    value_to_category_id = {}
    for legacy in legacy_values:
        title = mapping.get(legacy, legacy)
        slug = slugify(title, allow_unicode=True)
        category, _ = Category.objects.get_or_create(
            slug=slug,
            defaults={"title": title},
        )
        # if slug collision, still ensure title matches (best effort)
        if category.title != title:
            category.title = title
            category.save(update_fields=["title"])
        value_to_category_id[legacy] = category.id

    # assign FK
    for product in Product.objects.all().only("id", "category"):
        legacy = product.category
        category_id = value_to_category_id.get(legacy)
        if category_id:
            Product.objects.filter(id=product.id).update(category_new_id=category_id)


def backwards_noop(apps, schema_editor):
    # Best-effort noop: we don't restore the old string field.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0003_notificationrecipient_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="عنوان"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="نامک"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, unique=True, verbose_name="عنوان"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="نامک"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "برچسب",
                "verbose_name_plural": "برچسب\u200cها",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category_new",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="website.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                to="website.tag",
                verbose_name="برچسب\u200cها",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="قیمت (تومان)",
            ),
        ),
        migrations.RunPython(forwards_create_categories, backwards_noop),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="category_new",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="website.category",
                verbose_name="دسته\u200cبندی",
            ),
        ),
    ]
