# Generated by Django 6.0.4 on 2026-04-30 13:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0004_category_tag_alter_product_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("about", "درباره ما"),
                            ("contact", "تماس با ما"),
                            ("blog_post", "پست مجله"),
                        ],
                        max_length=20,
                        verbose_name="نوع صفحه",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=200, unique=True, verbose_name="نامک"
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(blank=True, max_length=300, verbose_name="خلاصه"),
                ),
                (
                    "featured_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="content/featured/",
                        verbose_name="تصویر شاخص",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True,
                        default="تیم ژیناد",
                        max_length=100,
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشر شده"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ انتشار"
                    ),
                ),
                ("views", models.IntegerField(default=0, verbose_name="تعداد بازدید")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "صفحه محتوا",
                "verbose_name_plural": "صفحات محتوا",
                "ordering": ["-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "block_type",
                    models.CharField(
                        choices=[
                            ("heading", "عنوان"),
                            ("rich_html", "متن (HTML)"),
                            ("image", "تصویر"),
                            ("callout", "کادر برجسته"),
                            ("divider", "جداکننده"),
                        ],
                        max_length=20,
                        verbose_name="نوع بلاک",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="عنوان"),
                ),
                (
                    "body_html",
                    models.TextField(blank=True, verbose_name="محتوا (HTML)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="content/blocks/",
                        verbose_name="تصویر",
                    ),
                ),
                (
                    "caption",
                    models.CharField(blank=True, max_length=300, verbose_name="کپشن"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="website.contentblock",
                        verbose_name="والد",
                    ),
                ),
                (
                    "page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="website.contentpage",
                        verbose_name="صفحه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بلاک محتوا",
                "verbose_name_plural": "بلاک\u200cهای محتوا",
                "ordering": ["parent_id", "order", "id"],
            },
        ),
    ]
