# Generated by Django 6.0.4 on 2026-04-30

from django.db import migrations
from django.utils.text import slugify


def _to_basic_html(text: str) -> str:
    if not text:
        return ""
    # Convert plain text to minimal HTML paragraphs.
    # Keep it simple and robust for migration purposes.
    parts = [p.strip() for p in text.replace("\r\n", "\n").split("\n\n") if p.strip()]
    return "".join(f"<p>{p.replace('\n', '<br>')}</p>" for p in parts)


def forwards(apps, schema_editor):
    ContentPage = apps.get_model("website", "ContentPage")
    ContentBlock = apps.get_model("website", "ContentBlock")
    BlogPost = apps.get_model("website", "BlogPost")
    SiteSettings = apps.get_model("website", "SiteSettings")

    # Ensure About + Contact exist (admin can edit later)
    about_page, _ = ContentPage.objects.get_or_create(
        slug="about",
        defaults={
            "page_type": "about",
            "title": "داستان ژیناد",
            "is_published": True,
        },
    )
    if not ContentBlock.objects.filter(page=about_page).exists():
        ContentBlock.objects.create(
            page=about_page,
            parent=None,
            order=1,
            block_type="heading",
            title="چگونه شروع شد",
            body_html="",
        )
        ContentBlock.objects.create(
            page=about_page,
            parent=None,
            order=2,
            block_type="rich_html",
            title="",
            body_html=_to_basic_html(
                "ژیناد از عشق به قهوه و شکلات آغاز شد.\n"
                "شما می‌توانید این متن را در پنل مدیریت ویرایش کنید."
            ),
        )

    contact_page, _ = ContentPage.objects.get_or_create(
        slug="contact",
        defaults={
            "page_type": "contact",
            "title": "تماس با ما",
            "is_published": True,
        },
    )
    if not ContentBlock.objects.filter(page=contact_page).exists():
        settings = SiteSettings.objects.first()
        phone = getattr(settings, "contact_phone", "") if settings else ""
        email = getattr(settings, "contact_email", "") if settings else ""
        address = getattr(settings, "address", "") if settings else ""
        contact_html = "<p>اطلاعات تماس را از پنل مدیریت ویرایش کنید.</p>"
        if phone:
            contact_html += f"<p><strong>تلفن:</strong> {phone}</p>"
        if email:
            contact_html += f"<p><strong>ایمیل:</strong> {email}</p>"
        if address:
            contact_html += f"<p><strong>آدرس:</strong> {address}</p>"

        ContentBlock.objects.create(
            page=contact_page,
            parent=None,
            order=1,
            block_type="heading",
            title="اطلاعات تماس",
            body_html="",
        )
        ContentBlock.objects.create(
            page=contact_page,
            parent=None,
            order=2,
            block_type="rich_html",
            title="",
            body_html=contact_html,
        )

    # Migrate BlogPost -> ContentPage(blog_post) + one rich_html block
    for post in BlogPost.objects.all():
        slug = post.slug or slugify(post.title, allow_unicode=True)
        # avoid slug conflicts with about/contact or other pages
        base_slug = slug
        i = 1
        while ContentPage.objects.filter(slug=slug).exists():
            i += 1
            slug = f"{base_slug}-{i}"

        page = ContentPage.objects.create(
            page_type="blog_post",
            title=post.title,
            slug=slug,
            excerpt=post.excerpt,
            featured_image=post.featured_image,
            author=post.author,
            is_published=post.is_published,
            published_at=post.published_at,
            views=post.views,
        )
        ContentBlock.objects.create(
            page=page,
            parent=None,
            order=1,
            block_type="rich_html",
            title="",
            body_html=_to_basic_html(post.content),
        )


def backwards(apps, schema_editor):
    # Non-destructive: keep migrated pages in place.
    return


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0005_contentpage_contentblock"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]

