# Generated by Django 6.0.4 on 2026-04-30 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0006_seed_content_pages_and_migrate_blogposts"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="footer_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/landing/",
                verbose_name="تصویر پس\u200cزمینه فوتر (اختیاری)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="logo_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site/branding/",
                verbose_name="لوگوی سایت (اختیاری)",
            ),
        ),
        migrations.CreateModel(
            name="HomeHeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="site/landing/hero/", verbose_name="تصویر"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hero_images",
                        to="website.sitesettings",
                        verbose_name="تنظیمات سایت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر هدر صفحه اصلی",
                "verbose_name_plural": "تصاویر هدر صفحه اصلی",
                "ordering": ["order", "id"],
            },
        ),
    ]
