# Generated by Django 6.0.4 on 2026-04-30 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_sitesettings_footer_image_sitesettings_logo_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="address_lat",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
                verbose_name="عرض جغرافیایی (Lat)",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="address_lng",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
                verbose_name="طول جغرافیایی (Lng)",
            ),
        ),
    ]
